const API_BASE="";const state={user:null,folder:"inbox",messages:[],selected:null};const $=s=>document.querySelector(s);const list=$("#list"),empty=$("#empty"),loginView=$("#loginView"),mailView=$("#mailView");const demoUsers={demo:{password:"demo1234",name:"Demo 사용자",email:"demo@resend.app"}};let demoMessages=[{id:"d1",folder:"inbox",from:"welcome@resend.app",to:"demo@resend.app",subject:"YouthDeveloper Mail에 오신 것을 환영합니다.",body:"메일 서비스 화면이 준비되었습니다. 실제 도메인과 수신 서버를 연결하면 이 화면 그대로 실사용할 수 있습니다.",date:new Date().toISOString(),read:false},{id:"d2",folder:"sent",from:"demo@resend.app",to:"test@example.com",subject:"테스트 메일",body:"테스트로 보낸 메일입니다.",date:new Date(Date.now()-86400000).toISOString(),read:true}];

function api(path,opts={}){if(!API_BASE)return Promise.reject(new Error("demo"));return fetch(API_BASE+path,{credentials:"include",headers:{"Content-Type":"application/json",...(opts.headers||{})},...opts}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"요청에 실패했습니다.");return d})}
function setMsg(t){$("#loginMsg").textContent=t||""}
function showMail(){loginView.classList.add("hidden");mailView.classList.remove("hidden");renderAccount();loadMessages()}
function renderAccount(){if(!state.user)return;$("#accountName").textContent=state.user.name||state.user.username;$("#accountEmail").textContent=state.user.email;$("#avatar").textContent=(state.user.name||state.user.username||"Y")[0].toUpperCase()}
async function login(username,password){try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({username,password})});state.user=d.user;showMail();return}catch(e){const u=demoUsers[username];if(u&&u.password===password){state.user={username,name:u.name,email:u.email};showMail();return}throw new Error("아이디 또는 비밀번호가 올바르지 않습니다.")}}
async function loadMessages(){try{const d=await api("/api/messages");state.messages=d.messages||[]}catch{state.messages=demoMessages.filter(m=>m.to===state.user?.email||m.from===state.user?.email)}render()}
function visible(){const q=$("#searchInput").value.trim().toLowerCase();return state.messages.filter(m=>m.folder===state.folder&&(!q||[m.from,m.to,m.subject,m.body].join(" ").toLowerCase().includes(q)))}
function render(){const items=visible();$("#folderTitle").textContent={inbox:"받은메일",sent:"보낸메일",trash:"휴지통"}[state.folder];list.innerHTML=items.map(m=>'<div class="mail-row '+(!m.read?"unread":"")+'" data-id="'+m.id+'"><div class="sender">'+escapeHtml(state.folder==="sent"?m.to:m.from)+'</div><div class="subject">'+escapeHtml(m.subject||"(제목 없음)")+' <span class="preview">'+escapeHtml((m.body||"").replace(/\s+/g," ").slice(0,70))+'</span></div><div class="date">'+formatDate(m.date)+'</div></div>').join("");empty.classList.toggle("hidden",items.length>0);$("#inboxCount").textContent=state.messages.filter(m=>m.folder==="inbox"&&!m.read).length||""}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function formatDate(v){const d=new Date(v);return isNaN(d)?v:d.toLocaleDateString("ko-KR",{month:"numeric",day:"numeric"})}
async function openMessage(id){const m=state.messages.find(x=>x.id===id);if(!m)return;state.selected=m;if(!m.read){m.read=true;try{await api("/api/messages/"+id,{method:"PATCH",body:JSON.stringify({read:true})})}catch{}}$("#readFrom").textContent=state.folder==="sent"?"받는 사람: "+m.to:"보낸 사람: "+m.from;$("#readSubject").textContent=m.subject||"(제목 없음)";$("#readMeta").textContent=new Date(m.date).toLocaleString("ko-KR");$("#readBody").textContent=m.body||"";$("#readDialog").showModal();render()}
async function deleteSelected(){const m=state.selected;if(!m)return;if(m.folder==="trash"){try{await api("/api/messages/"+m.id,{method:"DELETE"})}catch{}state.messages=state.messages.filter(x=>x.id!==m.id)}else{try{await api("/api/messages/"+m.id,{method:"PATCH",body:JSON.stringify({folder:"trash"})})}catch{}m.folder="trash"}$("#readDialog").close();render()}
async function sendMail(){const to=$("#toInput").value.trim(),subject=$("#subjectInput").value.trim(),body=$("#bodyInput").value.trim();if(!to||!subject||!body)return;$("#sendMsg").textContent="보내는 중…";try{await api("/api/send",{method:"POST",body:JSON.stringify({to,subject,body})});$("#sendMsg").textContent="";$("#composeDialog").close();await loadMessages()}catch{if(!state.user){return}demoMessages.unshift({id:"s"+Date.now(),folder:"sent",from:state.user.email,to,subject,body,date:new Date().toISOString(),read:true});$("#sendMsg").textContent="";$("#composeDialog").close();state.messages=demoMessages;render()}}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();setMsg("로그인 중…");try{await login($("#loginId").value.trim(),$("#loginPw").value);setMsg("")}catch(err){setMsg(err.message)}});$("#composeBtn").addEventListener("click",()=>{$("#sendMsg").textContent="";$("#composeForm").reset();$("#composeDialog").showModal()});$("#composeForm").addEventListener("submit",e=>{e.preventDefault();sendMail()});$("#searchInput").addEventListener("input",render);$("#refreshBtn").addEventListener("click",loadMessages);$("#logoutBtn").addEventListener("click",()=>{state.user=null;mailView.classList.add("hidden");loginView.classList.remove("hidden")});$("#folderNav").addEventListener("click",e=>{const b=e.target.closest("[data-folder]");if(!b)return;state.folder=b.dataset.folder;document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x===b));render()});list.addEventListener("click",e=>{const row=e.target.closest(".mail-row");if(row)openMessage(row.dataset.id)});$("#deleteReadBtn").addEventListener("click",deleteSelected);showLogin();
function showLogin(){loginView.classList.remove("hidden");mailView.classList.add("hidden")}
